### PR TITLE
Add directory for user natives to search path

### PR DESCRIPTION
**Pull request by JakubVanek**
This PR adds a directory for user-provided native libraries to the JNI library search path.

### CODE REVIEW

**Comment by jabrena** [comment]
We have to review it. We are mixing layers. Tomorrow, I will explain it in details.

Good night

**Comment by JakubVanek** [comment]
Oki, the idea behind this is that the user can now drop:
* their java libraries to `/home/robot/java/libraries` or wherever,
* the corresponding native libraries to `/home/robot/java/natives` and they are automatically found.

Alternatively, they can still install libraries through `apt-get`, it should work just as OpenCV works.

**Comment by jabrena** [comment]
hi @JakubVanek, 

The idea for `openjdk-ev3` is the build of non customized JDK. Current implementation:

```
JNI_PATH_FLAGS="--with-jni-libpath=/usr/lib/$DEB_HOST_MULTIARCH/jni:/lib/$DEB_HOST_MULTIARCH:/usr/lib/$DEB_HOST_MULTIARCH:/usr/lib/jni:/lib:/usr/lib"
```

Is enough for us. 

If we set the JDK with this proposal commit:

```
JNI_PATH_FLAGS="--with-jni-libpath=/home/robot/java/natives:/usr/lib/$DEB_HOST_MULTIARCH/jni:/lib/$DEB_HOST_MULTIARCH:/usr/lib/$DEB_HOST_MULTIARCH:/usr/lib/jni:/lib:/usr/lib"
``` 
   
We are coupling JDK layer with a specific implementation/design. Imagine that we use JDK from Oracle, we can't do this kind of settings, the same concept in our build.

If in the future, if someone need to use a native library, the user should locate the library on official path: `/usr/lib/$DEB_HOST_MULTIARCH/jni` or use the variable: `-Djava.library.path`, nothing more.

Indeed, if we add in that flag the path: `/home/robot/java/natives` we are coupling the JDK with a specific user.

Every layer should have some interface to interact but not mix:

- OS: Debian Stretch
- EV3Dev: Interface for Mindstorms Bricks IO
- JDK: OpenJDK (Stable, in maintain mode)
- Java library: Java library implementation to interact with EV3Dev

Juan Antonio

**Comment by JakubVanek** [comment]
Okay, I agree that this unnecessarily couples layers. Yup, users can just use the standard directories instead. Closing.

**Pull request closed without merging**
