### PR TITLE
Update host JDKs & decouple JDK versions from distro versions

### LINKED ISSUE #36: Decouple JDK version from distro version
Currently, the JDK12-JDK13 distro versions on native (arm) builders are locked together.
1. The config infrastructure can be prepared now.
2. After https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/674 is complete, the config can be filled in.

### PR DESCRIPTION
**Pull request by JakubVanek**
This PR updates Boot/Host JDK versions and splits the ARM-JDK12 to Buster & Stretch variants.

Before the job restructuring gets done, the script will now assume the following names:
* [x] [`openjdk12_build_ev3_linux_native`](https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk12_build_ev3_linux_native) for Stretch
* [x] [`openjdk12_build_ev3_linux_native_next`](https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk12_build_ev3_linux_native_next) for Buster

Note: merge after #38 , as this PR is built on top of that.
Fixes #36 
Not yet tested.

### CODE REVIEW

**Comment by jabrena** [comment]
Starting the review

**Comment by jabrena** [comment]
Zulu?

**Comment by JakubVanek** [comment]
I have changed the config to use AdoptOpenJDK builds everywhere.

**Comment by jabrena** [comment]
Tomorrow, I will continue with the review. Good night mate

**Comment by JakubVanek** [comment]
Partially tested - Prepare step indeed started downloading Adopt's OpenJDK12U for cross-stretch openjdk12_build_ev3_linux_native build for native-stretch.

Good night

**Review by jabrena — APPROVED** [review]

**Pull request merged**
